---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx
provisioner: driver.longhorn.io
parameters:
  accessMode: ReadWriteMany
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true