---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.yourdomain.com`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
          scheme: http
  tls:
    secretName: yoursecret-tls