---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yourdomain-com
  namespace: traefik
spec:
  secretName: yoursecret-tls
  dnsNames:
    - "yourdomain.com"
    - "*.yourdomain.com"
  issuerRef:
    name: cloudflare
    kind: Issuer
    name: cloudflare-production
  duration: 2160h # 90 days
  renewBefore: 168h # 7 days
