---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syjapp-com
  namespace: traefik
spec:
  secretName: syjapp-tls
  dnsNames:
    - "syjapp.com"
    - "*.syjapp.com"
  issuerRef:
    name: cloudflare
    kind: Issuer
  duration: 2160h # 90 days
  renewBefore: 168h # 7 days 